# Generated by Django 4.0.4 on 2022-06-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
